FROM docker.io/alpine

ARG TZ='Asia/Harbin'
ENV DEFAULT_TZ ${TZ}
ENV IN_CONTAINER yes
RUN --mount=target=/tmp-mount \
    apk upgrade --update \
    && apk add -U tzdata \
    && cp /usr/share/zoneinfo/${DEFAULT_TZ} /etc/localtime \
    && apk del tzdata \
    && rm -rf /var/cache/apk/*  && \
    chmod 600 /etc/passwd; \
    echo "deepflow:x:1000:1000::/home/deepflow:/bin/sh" >> /etc/passwd; \
    echo "root:root" | chpasswd; \
    chmod 000 /etc/passwd; \
    chmod 600 /etc/shadow; \
    echo "deepflow:!!:10000:0:99999:7:::" >> /etc/shadow; \
    chmod 000 /etc/shadow; \
    mkdir -p /lib64 && \
    cp -raf /tmp-mount/output/target/x86_64-unknown-linux-musl/release/deepflow-agent /bin/  && \
    cp -raf /tmp-mount/output/target/x86_64-unknown-linux-musl/release/deepflow-agent-ctl /bin/  && \
    cp -raf /tmp-mount/output/src/ebpf/deepflow-ebpfctl /bin/  && \
    chmod 4755 /bin/busybox && \
    mkdir -p /var/log/deepflow-agent && \
    chmod 0744 /var/log/deepflow-agent && \
    chown 1000:1000 /var/log/deepflow-agent && \
    chown 1000.1000 /bin/deepflow-agent

USER deepflow

CMD /bin/deepflow-agent -f /etc/deepflow-agent/deepflow-agent.yaml
